repos:
  - repo: local
    hooks:
      - id: trufflehog_scan
        name: Running Trufflehog scan
        entry: bash
        language: system
        pass_filenames: false   # weâ€™ll run the script on commit, not per file
        args: ["-c", "set -o pipefail; ~/.thog/scan_local_repo.sh | tee /dev/tty"]
