[tool.poetry]
name = "ssc-assignment-1"
version = "2.0.0"
description = ""
authors = ["Warren Pfeffer <wp732@nyu.edu>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "ssc_assignment_1"}]

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79		# strict PEP-8 wrapping at column 79
target-version = ['py311']

[tool.pylint.'MESSAGES CONTROL']
disable = [
	"too-many-arguments",
	"too-many-positional-arguments",
	"too-many-locals",
	"broad-exception-caught"
]
