[tool.poetry]
name = "wp732-rekor-tools"
version = "4.0.0"
description = "Tools to make using Rekor eaiser"
license = "Apache-2.0"
readme = "README.md"
authors = ["Warren Pfeffer <wp732@nyu.edu>"]

[[tool.poetry.packages]]
include = "wp732"
from = "src"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
jsonschema = ">=4.25.1,<5.0.0"
requests = ">=2.32.5,<3.0.0"
cryptography = ">=46.0.3,<47.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
