name: CI

on:
  push:
    branches:
      - 'testci'

jobs:
  test:
    runs-on: ubuntu-24.04-arm 
    container:
      image: ghcr.io/wp732/citool:latest
      options: --user root
      env:
        HOME: /home/user
        POETRY_VIRTUALENVS_PATH: /home/user/.cache/pypoetry/virtualenvs
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Add missing import packages
        run: bin/add_missing_imports.sh

#      - name: Run code formatting check via ruff
#        run: bin/run_ruff.sh --exclude tests/

#      - name: Run linting via pylint
#        run: bin/run_pylint.sh --disable=C0114,C0115,C0116
 
#      - name: Run SAST via bandit
#        run: bin/run_bandit.sh -f txt
 
      - name: Run type checking via mypy
        run: bin/run_mypy.sh
 
#      - name: Run unit tests via pytest
#        run: bin/run_pytests.sh

#      - name: Run code coverage check
#        run: bin/run_coverage_tests.sh
